### ISSUE TITLE
 - Radio program is not available: stremerror

### ISSUE THREAD

**Issue by trikinov** [odinuge/nrk-tv-downloader#11]
When downloading from 
https://radio.nrk.no/serie/radioteatret

With the following command : 
./nrk-tv-downloader.sh -a -n  https://radio.nrk.no/serie/radioteatret

It fails on season 2014 - first program

Says : 
 - Radio program is not available: stremerror  
many times, and halts...    This program should be unavailable, may be something wrong at NRK, but script should handle it...

**Comment by odinuge** [comment]
Hi,

I found a small bug, and this should hopefully be working in the dev branch.

Would be nice if you can report back the result.

To test the new version run the following:
```
git checkout dev
git pull
```

Thanks!

**Comment by trikinov** [comment]
Looks like it works......

Thank you...
