### ISSUE TITLE
the -a -n switch is not working anymore

### ISSUE THREAD

**Issue by greddost** [odinuge/nrk-tv-downloader#14]
Trying to download a complete series from super, stopped working.
Single episodes downloading from nrk super, but does not seem to work from tv.nrk.no...
Seems like they detect the script, says "Vi beklager"

example:
working:
http://tv.nrksuper.no/serie/mamma-moe-og-kraaka/OBUI59005305/sesong-1/episode-3

not working (worked before):
output:
./nrk-tv-downloader.sh -a -n https://tv.nrk.no/serie/peppa-gris/MSUI44005109/sesong-1/episode-52
Downloading "Vi beklager"
Downloading "Vi beklager"
Downloading "Vi beklager"

**Comment by odinuge** [comment]
Thanks @greddost!

Will look at it!

**Comment by odinuge** [comment]
Hi,

Feel free to look at #15, as it should fix the problem. The only change was some html-properties nrk removed, but everything should work now.

To test it, checkout the `dev` branch, and then pull the new changes;
```
git checkout dev
git pull
./nrk-tv-downloader.sh "yourstuff"
```

**Comment by odinuge** [comment]
Guess this works now :smile:
