### ISSUE TITLE
Problemer med nedlasting av radioprogram

### ISSUE THREAD

**Issue by Kvaks** [odinuge/nrk-tv-downloader#20]
Hei! Takk for en fin og praktisk nedlaster! Har nyeste versjon etter siste ukers endringer, men får feilmelding på følgende radioprogram (andre har fungert):

https://radio.nrk.no/serie/atlantis/MUHR39001717/23-04-2017

**Comment by odinuge** [comment]
Hei!

Tusen takk for det, flott å høre! :)

Ja, det var en liten bug i den _primitive_ json-parsingen, som mest sansynlig skal være fikset i #21. Fint om du også kan teste og gi tilbakemelding. Skal også teste litt med andre ting, før jeg pusher det til `master`.

Ha en fin kveld videre! :smiley:

**Comment by Kvaks** [comment]
Jepp, den fiksen fikset dette problemet.
