### ISSUE TITLE
Local filename format

### ISSUE THREAD

**Issue by eithe** [odinuge/nrk-tv-downloader#23]
This is a future request for the downloader to name programs that are based on seasons and episodes in a format that allows content scanners to read out the season and episode numbers from the filenames. My personal preference is Name.Of.Show.SXXEXX.mp4 (e.g. Arkitektens.hjem.S01E04.mp4), but perhaps it can be customizable by the user.

I have a hacked together version (I'm no bash scripter) of this running locally using the format above. I'll see if I can make it release friendly and submit a PR later, just wanted to get the idea out there and perhaps get some input.

**Comment by odinuge** [comment]
Hi,

I totally agree! :+1: I have no special reason for using the current naming scheme, it was initially created to remove/replace characters that doesn't work _that well_ in "unix-land" (spaces, colons, æøå etc.).

Feel free to send your code as a PR, that would be a nice place to start!

**Comment by ralin3** [comment]
That would simply be awesome! 
Can I recommend also removing the following  filenaming:
Barnas_supershow_-_musikkvideo_\Tissetrengt\_24.11.2014.mp4
\ breaks havoc for Kodi when shared over cifs. 



On Mon, May 8, 2017, at 11:37, Odin Ugedal wrote:
> Hi,


> I totally agree! 👍 I have no special reason for using the current
> naming scheme, it was initially created to remove/replace
> characters that doesn't work *that well* in "unix-land" (spaces,
> colons, æøå etc.).> Feel free to send your code as a PR, that would be a nice place
> to start!> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/odinuge/nrk-tv-downloader/issues/23#issuecomment-299843901

**Comment by eithe** [comment]
I'll do some quick mods and publish tonight. Not sure how robust is it yet,
though.. :)

**Comment by eithe** [comment]
PR https://github.com/odinuge/nrk-tv-downloader/pull/25 is a starting point at least, but I'm not sure it'll work for all series. It's been working for me for a while, though. The code can be simplified and better explained, I'll leave that to @odinuge if he wants to include this, I'll be afk for the next 1-2 weeks.

I was also planning to add a flag to store the downloaded file(s) in a folder structure (e.g. ./Series.name/Season xx/Series.name.SxxExx.mp4)

**Comment by odinuge** [comment]
Good work @eithe! :smile:

I have quite a few uni exams the next month, so I am unsure about when I have time to look at it myself. The folder structure you suggests would also be an awesome addon! :+1:

Dedicated branch (with @eithe's initial work) that everyone can send their PR's related to this issue/enhancement: [filename_schema](https://github.com/odinuge/nrk-tv-downloader/tree/filename_schema)

**Comment by eithe** [comment]
Teaser:

    ./nrk-tv-downloader.sh -anueft /mnt/media/Kids https://tv.nrk.no/serie/lesekorpset/
    Program "Lesekorpset"
    - /mnt/media/Kids/Lesekorpset/Season 01/Lesekorpset.S01E01.mp4 exists, overwrite? [y/N]:
    - Skipping program, already downloaded

**Comment by ralin3** [comment]
Skip the spaces maybe?

**Comment by odinuge** [comment]
Closed via #27. Thanks to @eithe! :smile: 

Implemented with this schema: https://support.plex.tv/hc/en-us/articles/200220687-Naming-Series-Season-Based-TV-Shows.

Stuff like extra-seasons is missing, but that can be fixed in another PR.
