### ISSUE TITLE
Change output filename format

### ISSUE THREAD

**Issue by drtomasso** [odinuge/nrk-tv-downloader#26]
Hi

Could there be an option (or change the current default) to use a more media server friendly name?

Should be `Series Name S[xx]E[xx]-[Optional episode name]`

**Comment by eithe** [comment]
Hi, this is related to https://github.com/odinuge/nrk-tv-downloader/issues/23. I have a [commit for what you are looking for](https://github.com/eithe/nrk-tv-downloader/commit/feeb27d952b626b98818a8a87b45ab5d1f5fb9a6) [in my fork](https://github.com/eithe/nrk-tv-downloader), but it's not very robust yet.

**Comment by drtomasso** [comment]
Ah, I missed that issue. Closing this then, since it's a duplicate.

**Comment by odinuge** [comment]
Nice work @eithe. Will look at (and hopefully get it into master) tomorrow :smile: 

CC: @drtomasso
