### ISSUE TITLE
"stremerror" ved nedlasting

### ISSUE THREAD

**Issue by kjetilk** [odinuge/nrk-tv-downloader#29]
Hei!

Jeg får ikke skriptet til å funke nå om dagen. Får en kryptisk feilmelding, f.eks.:
```
kjetil@tigger:/mnt/store-c/serier/Kaptein_Sabeltann-Kongen_på_havet$ nrk-tv-downloader.sh  -a -u -e https://tv.nrk.no/serie/kaptein-sabeltann
Available seasons of "kaptein-sabeltann": 1
Available episodes in "Kaptein Sabeltann, sesong: 1": 11
Program "Kaptein Sabeltann - Kongen på havet 22:26"
 - Tv program is not available: stremerror

Program "Kaptein Sabeltann - Kongen på havet 21:26"
 - Tv program is not available: stremerror
```
og
```
kjetil@tigger:/mnt/store-c/serier/Karsten_og_Petra$ nrk-tv-downloader.sh -a -u -e https://tv.nrk.no/serie/karsten-og-petra
Available seasons of "karsten-og-petra": 6
Available episodes in "Karsten og Petra, sesong: 6": 10
Program "Karsten og Petra 10:10"
 - Tv program is not available: stremerror

Program "Karsten og Petra 9:10"
 - Tv program is not available: stremerror
```
osv.

Noen ideer om hva som kan være galt her?

**Comment by odinuge** [comment]
Hei,
Tusen takk for beskjeden. Skal prøve å få sett på det når jeg får tid.

**Comment by greddost** [comment]
Samme feil her, antakelig endringer hos nrk igjen

**Comment by Eightyplus** [comment]
Får samme feil

**Comment by Eightyplus** [comment]
Får samme feil, kan se `$stream` er to konkatinerte URL, kanskje den må splittes!?

`http://nordond9c-f.akamaihd.net/i/no/open/84/*********'-,.mp4.csmil/http://nordond9c-f.akamaihd.net/i/no/open/84/.********.,.mp4.csmil/index_4_av.m3u8?null=0 - Length: 00:00:00`

**Comment by odinuge** [comment]
Hei,
Tror #31 skal fikse biffen. Du kan teste det i `master`-branchen, og lukke issuen hvis alt funker som det skal! :smile:

**Comment by kjetilk** [comment]
Jepp, den funker, tusen takk!
