### ISSUE TITLE
Den Blå Planeten // Men tror layout er helt endret

### ISSUE THREAD

**Issue by ralin3** [odinuge/nrk-tv-downloader#35]
Følgende fungerer ikke:
https://tv.nrk.no/serie/den-blaa-planeten

Men ser at hele layouten til NRK er endret, så det er sikkert derfor!

**Comment by odinuge** [comment]
Hei,

Tusen takk for beskjeden. Ser ut som det er blitt gjort ganske store API- (skikkelig bra) og HTML-layouten, slik at parsingen ikke lenger fungerer helt optimal. Har fikset nedlasting av enkeltepisoder i #37, hvor det også står litt mer utfyllende om problemene.

Ha en fortreffelig uke videre!
