### ISSUE TITLE
URLs have changed; cannot download episodes when rights expired

### ISSUE THREAD

**Issue by kjetilk** [odinuge/nrk-tv-downloader#39]
It seems like URLs have changed, and I wonder if that causes some problems. 

This is the problem I'm struggling with:

```
$ nrk-tv-downloader.sh -n -d -u https://tv.nrk.no/serie/kaptein-sabeltann/sesong/1/episode/19/
Program "Kaptein Sabeltann - Kongen på havet 1:26"
 - Tv program is not available:  program rights has expired
```

There may be several problems, one is that the URL seemingly has changed. One is that it first tries to download episode 1, when it was supposed to get episode 19. The last is that it gives up because the rights for episode 1 has expired. I don't know which is actually the root cause here.

**Comment by odinuge** [comment]
Did you get it working @kjetilk?

Just comment, and ill open the issue if it still doesn't work.

**Comment by kjetilk** [comment]
Actually, I don't know, since I'm not aware of a series right now that has partially expired. I'll comment again if I find something.
