### ISSUE TITLE
Subtitles isn't being downloaded anymore

### ISSUE THREAD

**Issue by zackern** [odinuge/nrk-tv-downloader#41]
It seems like the program isn't downloading subtitles anymore.
There is no error messages it just doesnt download them,
Maybe the API changed?

**Comment by odinuge** [comment]
Hi! @zackern 

Strange :thinking: Works well for me.

Are you sure you downloaded `tt-to-subrip` by cloning with `--recursive`? If the folder `tt-to-subrip` is missing, or is emptry, you can run `git submodule update --init --recursive` to download it. :smile:

**Comment by smagnusson** [comment]
@zackern I have the same issue. In the source code I changed  http://v8.psapi.nrk.no/programs/$program_id/subtitles/tt to http://psapi.nrk.no/programs/$program_id/subtitles/tt and it works for me now.

**Comment by odinuge** [comment]
Should hopefully be fixed by #48
