### ISSUE TITLE
syntax error: operand expected (error token is "/")

### ISSUE THREAD

**Issue by ralin3** [odinuge/nrk-tv-downloader#6]
Trying to run ./NRK-TV-Downloader.sh -a https://tv.nrk.no/serie/musti
Ends up with:
NRK-TV-Downloader.sh: line 219: (0*100)/: syntax error: operand expected (error token is "/")

**Comment by drtomasso** [comment]
Same with:
```bash
./NRK-TV-Downloader.sh https://tv.nrk.no/serie/over-hekken/MUHH48006115/sesong-2/episode-1
```

Looks like this error occures when it fails to read the lenght of the media

**Comment by odinuge** [comment]
That is strange.. I'll look into it!

**Comment by drtomasso** [comment]
Great work, thanks!

**Comment by ralin3** [comment]
This doesn't work with latest version: 0.9.91
Downloading "Musti 12:52 sesong-1"
awk: line 2: syntax error at or near ,
awk: line 3: syntax error at or near ,
 - Program is not available: streamerror

**Comment by odinuge** [comment]
What distro are you runnning?
You can also try to download gawk, and see what happens..

**Comment by ralin3** [comment]
Running Debian Stable, with a minimal install - gawk is not installed.
Installing gawk makes it work, so yeah - that was it.
