### ISSUE TITLE
Could you help to mention the dependencies?

### ISSUE THREAD

**Issue by liangqi** [odinuge/nrk-tv-downloader#7]
For example, which linux distribution are you using? And version info for ffmpeg, avconv, etc? Thanks.

**Comment by ralin3** [comment]
I'm using it with Debian Jessie amd64.
I have installed gawk (v4.1.1) and ffmpeg (v2.6.5)

**Comment by odinuge** [comment]
Hello,
I am using Arch Linux, with:
- gawk: 4.1.3
- ffmpeg: 2.8.1
- bash: 4.3.42

I have also tested with Debian (avconv & gawk).

Are you having any problems, or are you just wondering? If you have any problems, feel free to open an issue.

I just added gawk as a dependency, which most likely will fix problems for a lot of people running other distros.

**Comment by odinuge** [comment]
A list of deps can be found [here!](https://github.com/odinuge/nrk-tv-downloader/blob/master/nrk-tv-downloader.sh#L33). ffmpeg or avconv is also required.
