### ISSUE TITLE
Tv program is not available

### ISSUE THREAD

**Issue by eithe** [odinuge/nrk-tv-downloader#9]
Hi, using the latest version on Mac OS X (with gawk, ffmpeg and other dependencies installed), I get:

    TV:nrk tv$ ./nrk-dl.sh https://tv.nrk.no/serie/thomas-og-vennene-hans/MSUI21004115/sesong-1/episode-1
    Downloading ""
    ./nrk-dl.sh: line 393: [: ==: unary operator expected
     - Tv program is \e[31mnot available\e[0m:

Guessing it's a bit difficult for you to debug on mac, but got an idea on where I should start looking?

**Comment by odinuge** [comment]
Hi,

I'm unable to reproduce your problem here. I only have linux.

Can you send me the result of ´´´git describe --always´´´ (where you are in the history), and also checkout the dev branch and test that.

**Comment by eithe** [comment]
TV:nrk-tv-downloader tv$ git describe --always
    29f1bbe

Checking out dev:

    TV:nrk-tv-downloader tv$ git checkout
    Your branch is up-to-date with 'origin/master'.
    TV:nrk-tv-downloader tv$ git checkout dev
    Branch dev set up to track remote branch dev from origin.
    Switched to a new branch 'dev'
    TV:nrk-tv-downloader tv$ git pull
    Already up-to-date.
    TV:nrk-tv-downloader tv$ git describe --always
    a2e3132

Trying to dl:

    TV:nrk-tv-downloader tv$ ./nrk-tv-downloader.sh https://tv.nrk.no/serie/thomas-og-vennene-hans/MSUI21004115/sesong-1/eisode-1
    Downloading ""
     - Subtitle is not available
     -Tv  program is \e[31mnot available\e[0m:

    TV:nrk-tv-downloader tv$

Anyway, I debugged a bit myself and I noticed the v8 api mediaelement request failed with a 404 which enabled me to notice that the programid was not retrieved correctly from the html. `gethtmlMeta`  actually ends up always retrieving the last media element (which happens to be google-site-verification). Will report back here or submit a pull request when I'm able to fix it.

**Comment by eithe** [comment]
Seems like the fix is just to use gawk instead of awk. I /s/awk/gawk on nrk-tv-downloader.sh and now it hums along nicely :)

**Comment by odinuge** [comment]
That sounds great! Feel free to send a PR to `dev`, and i will be happy to merge it!

**Comment by eithe** [comment]
No problem; https://github.com/odinuge/nrk-tv-downloader/pull/10

You specifically need to test if your tt to subrip still works fine.
